### ISSUE TITLE
Can't activate EDI Relevant Odoo9

### ISSUE THREAD

**Issue by mlbah** [clubit/edi-workflow#2]
Hi,

can you please help, I am getting this error below when I want to select a partner as **EDI Relevant** in Odoo 9.

thank you,

Traceback (most recent call last):
  File "/home/mlbah/Odoo/odoo9/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mlbah/Odoo/odoo9/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/mlbah/Odoo/odoo9/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/mlbah/Odoo/odoo9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/mlbah/Odoo/odoo9/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/mlbah/Odoo/odoo9/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/home/mlbah/Odoo/odoo9/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/home/mlbah/Odoo/odoo9/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/mlbah/Odoo/odoo9/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/mlbah/Odoo/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/mlbah/Odoo/odoo9/edi-workflow-9.0-dev/edi_tools/models/partner.py", line 27, in write
    self.maintain_edi_directories(cr, uid, ids, context)
  File "/home/mlbah/Odoo/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/mlbah/Odoo/odoo9/edi-workflow-9.0-dev/edi_tools/models/partner.py", line 46, in maintain_edi_directories
    edi_directory = self.pool.get('ir.values').get_defaults_dict(cr, uid, 'edi.tools.config.settings')['edi_root_directory']
KeyError: 'edi_root_directory'

**Comment by dimitriverhelst** [comment]
you have to set the edi root folder in EDI settings.
make sure permissions match odoo's permissions.
